## YAML Template.
---
version: '3.8'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # Puerto externo para tus apps
      - "29092:29092" # Puerto interno para otros contenedores (útil en clusters)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      
#  mysql:
#    image: mysql:8
#    container_name: mysql-db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: fideicomisos
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  auth-service:
#    build: ./backend/auth-service
#    ports:
#      - "8081:8080"
#    depends_on:
#      - mysql
#
#  core-service:
#    build: ./backend/core-service
#    ports:
#      - "8082:8080"
#    depends_on:
#      - mysql
#
#  reportes-service:
#    build: ./backend/reportes-service
#    ports:
#      - "8083:8080"
#    depends_on:
#      - mysql
#
#  api-gateway:
#    build: ./backend/api-gateway
#    ports:
#      - "8080:8080"
#    depends_on:
#      - auth-service
#      - core-service
#      - reportes-service
#
#  frontend:
#    build: ./frontend/fideicomisos-app
#    ports:
#      - "4200:4200"
#    depends_on:
#      - api-gateway
#
#volumes:
#  mysql_data: